name: CI

on:
  push: {}
  pull_request: {}

jobs:
  tests:
    timeout-minutes: 5
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.7.0
          # cache: npm
      - run: bun install
      - run: bun lint
      - run: bun test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info
      - run: bunx lcov-summary coverage/lcov.info >> "$GITHUB_STEP_SUMMARY"
