name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    uses: jondotsoy/jondotsoy/.github/workflows/bun-release-package.yml@v1
    permissions:
      contents: write
      pull-requests: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  prepare:
    needs:
      - release
    runs-on: ubuntu-latest
    if: ${{ !needs.release.outputs.prs_created }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ fromJson(needs.release.outputs.pr).headBranchName }}
      - name: build version file
        run: |
          make build_version_file
      - name: commit version change
        continue-on-error: true
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add src/actioman-version.ts
          git commit -m "chore: upgrade actioman-version.ts"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ fromJson(needs.release.outputs.pr).headBranchName }}
